<?php
require_once '../../function/db.php';
$idr=$_POST['rowid'];
$cek="SELECT * FROM raport_k13 WHERE id_raport='$idr'";
$hasil=mysqli_query($koneksi,$cek);
$utt=mysqli_fetch_array($hasil);
$idsis=$utt['id_pd'];
$idmp=$utt['mapel'];
$nsiswa=mysqli_fetch_array(mysqli_query($koneksi,"select * from siswa where peserta_didik_id='$idsis'"));
$nmp=mysqli_fetch_array(mysqli_query($koneksi,"select * from mapel where id_mapel='$idmp'"));
?><div class="modal-body">							<div class="form-group form-group-default">								<label>Nama Siswa</label>								<input type="hidden" name="idraport" class="form-control" value="<?php echo $utt['id_raport'];?>">								  <input type="hidden"  name="ids" class="form-control" value="<?php echo $nsiswa['peserta_didik_id'];?>">								  <input type="hidden" name="kelas" class="form-control" value="<?php echo $utt['kelas'];?>">								  <input type="hidden" name="smt" class="form-control" value="<?php echo $utt['smt'];?>">								  <input type="hidden" name="tapel" class="form-control" value="<?php echo $utt['tapel'];?>">								  <input type="hidden" name="kelas" class="form-control" value="<?php echo $utt['kelas'];?>">								  <input type="hidden" name="mapel" class="form-control" value="<?php echo $utt['mapel'];?>">								  <input type="hidden" name="jns" class="form-control" value="<?php echo $utt['jns'];?>">								  <input type="text" class="form-control" value="<?=$nsiswa['nama'];?>" name="nama">							</div>							<div class="form-group form-group-default">								<label>Mata Pelajaran</label>								<input type="text" class="form-control" value="<?=$nmp['nama_mapel'];?>" name="mp">							</div>							<div class="form-group form-group-default">								<label>Nilai</label>								<input type="text" class="form-control" value="<?=number_format($utt['nilai'],0);?>" name="nilai">							</div>							<div class="form-group form-group-default">								<label>Predikat</label>								<select class="form-control" name="predikat">									<option value="A" <?php if($utt['predikat']=="A"){echo "selected";} ?>>A</option>									<option value="B" <?php if($utt['predikat']=="B"){echo "selected";} ?>>B</option>									<option value="C" <?php if($utt['predikat']=="C"){echo "selected";} ?>>C</option>									<option value="D" <?php if($utt['predikat']=="D"){echo "selected";} ?>>D</option>									<option value="E" <?php if($utt['predikat']=="E"){echo "selected";} ?>>E</option>								</select>							</div>							<div class="form-group form-group-default">								<label>Deskripsi Raport</label>								<textarea name="deskripsi" class="form-control" rows="4" aria-label="With textarea"><?=$utt['deskripsi'];?></textarea>							</div>                        </div>                        <div class="modal-footer">                            <button type="button" class="btn btn-info btn-border btn-round btn-sm" data-dismiss="modal">Tutup</button>							<button type="submit" class="btn btn-info btn-border btn-round btn-sm">Simpan</button>						</div>
						